### ISSUE TITLE
REST endpoints Get Confirmed Transactions

### ISSUE THREAD

**Issue by aenhsaihan** [aenhsaihan/McCoin#25]
if you ask different nodes about transactions, they might give you different data

confirmed transactions though are immutable

different nodes hold different state

they will be synchronized eventually

**Comment by aenhsaihan** [comment]
all transactions have a hash, pending and unsigned transactions also have data hash (unique ID)

this allows you to create a transaction through any medium such as skype, and the other party can sign the transaction

**Comment by sirgillif** [comment]
I'm closing this issue. Our wallet, handles this problem and should technically allow for offline transactions
