### ISSUE TITLE
processing a mined block

### ISSUE THREAD

**Issue by aenhsaihan** [aenhsaihan/McCoin#37]
miners submit their mined block hash

when miner submits a PoW hash

the node finds the block candidate by its blockDataHash
the node verifies the hash + its difficulty and build the next block
the block candidate is merged with the nonce + timestamp + hash

then if the block is still not mined, the chain is extended
sometimes other miners can be faster -> the mined block is expired

then all peers are notified about the new mined block

**Comment by sirgillif** [comment]
I believe this issue has been resolved, our miner works with the NakovChain on properly submitting the mined block, our current blockchain updates its peers of the new mined block. I think that any issues technically remaining on this are outside the scope of this particular problem.

**Comment by 24thsaint** [comment]
I don't think we can close this now. Currently, the node does not validate the submitted block yet.

```javascript
// burgerNode
    addMinedBlock(minedBlock) {
        this.chain.addMinedBlock(minedBlock);
    }
// =========================
// burgerBlockchain
    addMinedBlock(minedBlock) {
      let block = this.miningJobs.get(minedBlock.blockDataHash);

      const {
        nonce,
        dateCreated,
        hash
      } = minedBlock;

      block.nonce = nonce;
      block.dateCreated = dateCreated;
      block.blockHash = hash;

      if (this.canAddBlock(block)) {
        this.addBlock(block);
        this.miningJobs.delete(block.blockHash);
        console.log('Submitted block has been added to chain');
      } else {
        console.log('Submitted block has failed to be added to chain');
      }
    }

    canAddBlock(block) {
        const lastBlock = this.getLastBlock();

        if (block.index > lastBlock.index) {
            return true;
        } else {
            return false;
        }
    }

    addBlock(block) {
        this.flushPendingTransactions(block);
        this.blocks.push(block);
    }
```
