### ISSUE TITLE
REST Endpoint: Submit Block

### ISSUE THREAD

**Issue by aenhsaihan** [aenhsaihan/McCoin#38]
/mining/submit-mined-block

the miner is rewarded for mining the block using the address that was provided by the miner

if two blocks are discovered at nearly the same time, 

there could be a conflict

part of the network will use one block, and the other part the other block

ethereum uses uncle blocks to resolve this issue

**Comment by 24thsaint** [comment]
I'm also confused by this... Are we required to implement the 'uncles' thing?
